{% set version = "0.2.0" %}

package:
  name: jupyter_server_terminals_proxy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyter-server-terminals-proxy/jupyter_server_terminals_proxy-{{ version }}.tar.gz
  sha256: 71edd36463880318d4b6707e5deab1052e900532f4d203667f2cff6c29e33a5a

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - hatchling
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - anyio >=4.3.0,<5.0.0
    - httpx >=0.27.0,<0.28
    - httpx-ws >=0.6.0,<0.7.0
    - jupyter_server >=1.0.0,<3.0.0

test:
  imports:
    - jupyter_server_terminals_proxy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/davidbrochart/jupyter_server_terminals_proxy
  summary: A Jupyter Server Extension Proxying Terminals.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - davidbrochart
