{% set version = "0.1.3" %}

package:
  name: jupyter_server_terminals_proxy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyter-server-terminals-proxy/jupyter_server_terminals_proxy-{{ version }}.tar.gz
  sha256: 1f4d64cb9f0441d2646b6156ea3bb69c30bbdbba9f61b2d30e4d3bb28650f918

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - hatchling
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - jupyter_server >=1.0.0
    - httpx >=0.23.1
    - websockets >=10.4

test:
  imports:
    - jupyter_server_terminals_proxy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/davidbrochart/jupyter_server_terminals_proxy
  summary: A Jupyter Server Extension Proxying Terminals.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - davidbrochart
